[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
NUXT_SUPABASE_URL = "https://zeqpgwdworgybkfjgxwk.supabase.co"
NUXT_SUPABASE_ANON_KEY = "sb_secret_jq79sSAaBb1rZU88VtRlHA_MBYR7gSz"
